### ISSUE TITLE
Smarty string resource breaks when using variable modifiers

### ISSUE THREAD

**Issue by davexunit** [zyxware/civiwci#32]
Here's an abridged version of some code in `CRM/Wci/WidgetCode.php`:

```php
$template = CRM_Core_Smarty::singleton();
$wcidata = $template->fetch('string:' . html_entity_decode($data['custom_template']));
```

For some reason, if the Smarty template contained within that string contains a variable modifier like `{ $foo | number_format }`, the template rendering breaks.  As a hack, I escaped all of the `|` characters in the string, and it worked... sort of.  I was able to use the [built-in variable modifiers](http://www.smarty.net/docsv2/en/language.modifiers.tpl) but not PHP functions like `number_format`.

This issue prevents customized widget templates from working like the built-in one.  To reproduce, just customize the widget and paste in the default template in the advanced options area.

Thoughts?  Is this a Smarty deficiency or is something else wrong here?  I sank a bunch of time into it a couple of weeks ago and couldn't resolve the issue.

**Comment by vimaljoseph** [comment]
This is due to a security feature in CiviCRM . The CRM_Core_Smarty class overrides the fetch method to enable the security mode of Smarty if the template is loaded from a string. If security mode is enabled, smarty will not allow php functions.

We can override the secuity_settings with the php functions we require in the template by adding
```php
$template->security_settings['MODIFIER_FUNCS'] = array('number_format', 'count');
```
Before fetching the template from string. What is your take on this? Is there any other php function you think that is useful in the template?

**Comment by davexunit** [comment]
Cherry picking some modifier functions would work for our immediate needs, but it would lead to confusion down the road when someone who wasn't aware of this restriction (like I was) tried to use a function that wasn't blessed.

I checked out the implementation of `fetch` in `CRM_Core_Smarty`, and it forces the security setting, so I don't have a great suggestion about how to circumvent it for a special case.

So, how about we do the cherry picking method for now?  `number_format` and `count` are good to have, but I don't write enough PHP to know which other ones would be essential.  Feel free to add more if you can think of them.

Thanks!

**Comment by vimaljoseph** [comment]
OK. I add number_format to the list as the default tempalte is using that Also I have mentioned this in the help text for custom template text area. Pushed the changes to master.

**Comment by davexunit** [comment]
Thanks @vimaljoseph!
